<a href="https://colab.research.google.com/github/adhikaryramen87/MachineLearning_Works/blob/main/Text_Vectorization_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import all the required libraries

In [ ]:
import pandas as pd
import numpy as np

Load the data

In [ ]:
data = pd.read_csv('/content/spam.csv')
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
data['spam'] = data['Category'].apply(lambda x:1 if x == 'spam' else 0)
data.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Data Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.Message, data.spam, stratify=data.spam, test_size=0.2, random_state=42)

In [ ]:
X_train[:4]

184                              He will, you guys close?
2171    CAN I PLEASE COME UP NOW IMIN TOWN.DONTMATTER ...
5422              Ok k..sry i knw 2 siva..tats y i askd..
4113                            I'll see, but prolly yeah
Name: Message, dtype: object

In [ ]:
X_train.shape

(4457,)

Message -> Feature Vectorization

In [ ]:
X_train.values

array(['He will, you guys close?',
       'CAN I PLEASE COME UP NOW IMIN TOWN.DONTMATTER IF URGOIN OUTL8R,JUST REALLYNEED 2DOCD.PLEASE DONTPLEASE DONTIGNORE MYCALLS,U NO THECD ISV.IMPORTANT TOME 4 2MORO',
       'Ok k..sry i knw 2 siva..tats y i askd..', ...,
       'Moby Pub Quiz.Win a £100 High Street prize if u know who the new Duchess of Cornwall will be? Txt her first name to 82277.unsub STOP £1.50 008704050406 SP Arrow',
       "Free entry in 2 a weekly comp for a chance to win an ipod. Txt POD to 80182 to get entry (std txt rate) T&C's apply 08452810073 for details 18+",
       'We are at grandmas. Oh dear, u still ill? I felt Shit this morning but i think i am just hungover! Another night then. We leave on sat.'],
      dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_train_cv = vectorizer.fit_transform(X_train.values)
type(X_train_cv)

scipy.sparse._csr.csr_matrix

In [ ]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58884 stored elements and shape (4457, 7663)>

4457 => number of messages in the dataframe

7663 => number of unique words/features in the messages

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectorizer.get_feature_names_out()[3000:6000]

array(['fren', 'french', 'frens', ..., 'sha', 'shade', 'shadow'],
      dtype=object)

In [ ]:
vectorizer.vocabulary_

{'he': 3368,
 'will': 7434,
 'you': 7624,
 'guys': 3285,
 'close': 1856,
 'can': 1641,
 'please': 5205,
 'come': 1914,
 'up': 7102,
 'now': 4807,
 'imin': 3624,
 'town': 6922,
 'dontmatter': 2415,
 'if': 3603,
 'urgoin': 7128,
 'outl8r': 4976,
 'just': 3868,
 'reallyneed': 5553,
 '2docd': 387,
 'dontplease': 2416,
 'dontignore': 2414,
 'mycalls': 4640,
 'no': 4765,
 'thecd': 6743,
 'isv': 3754,
 'important': 3632,
 'tome': 6876,
 '2moro': 400,
 'ok': 4884,
 'sry': 6371,
 'knw': 3957,
 'siva': 6143,
 'tats': 6643,
 'askd': 1100,
 'll': 4152,
 'see': 5928,
 'but': 1587,
 'prolly': 5398,
 'yeah': 7596,
 'swing': 6590,
 'by': 1602,
 'in': 3643,
 'bit': 1375,
 'got': 3204,
 'some': 6245,
 'things': 6770,
 'to': 6854,
 'take': 6616,
 'care': 1662,
 'of': 4859,
 'here': 3415,
 'firsg': 2882,
 'shall': 6006,
 'book': 1435,
 'chez': 1783,
 'jules': 3859,
 'for': 2946,
 'half': 3305,
 'eight': 2554,
 'that': 6734,
 'with': 7465,
 'thanks': 6728,
 'your': 7628,
 'message': 4439,
 'really': 5552,
 'appreciate': 1038,
 'sacrifice': 5817,
 'not': 4793,
 'sure': 6558,
 'the': 6738,
 'process': 5385,
 'direct': 2341,
 'pay': 5079,
 'find': 2864,
 'out': 4970,
 'on': 4903,
 'my': 4639,
 'way': 7326,
 'back': 1199,
 'from': 3027,
 'test': 6707,
 'tomorrow': 6880,
 'class': 1838,
 'do': 2377,
 'have': 3359,
 'wonderful': 7496,
 'day': 2187,
 'feb': 2808,
 'lt': 4239,
 'gt': 3264,
 'is': 3743,
 'love': 4217,
 'send': 5953,
 'dis': 2346,
 'all': 917,
 'ur': 7121,
 'valued': 7168,
 'frnds': 3020,
 'evn': 2692,
 'me': 4392,
 'comes': 1916,
 'married': 4348,
 'person': 5123,
 'luv': 4254,
 'ignore': 3607,
 'lose': 4197,
 'evr': 2695,
 'chinese': 1802,
 'food': 2938,
 'its': 3761,
 'when': 7398,
 'get': 3123,
 'fat': 2792,
 're': 5534,
 'paying': 5084,
 'lipo': 4131,
 'free': 2990,
 'nokia': 4773,
 'or': 4940,
 'motorola': 4575,
 'upto': 7119,
 '12mths': 286,
 '2price': 414,
 'linerental': 4120,
 '500': 543,
 'net': 4716,
 'mins': 4475,
 '100txt': 259,
 'mth': 4601,
 'tooth': 6898,
 'call': 1617,
 'mobileupd8': 4523,
 '08001950382': 50,
 '2optout': 412,
 'd3wv': 2148,
 'jus': 3867,
 'came': 1637,
 'fr': 2979,
 'lunch': 4250,
 'wif': 7425,
 'sis': 6132,
 'only': 4915,
 'leh': 4064,
 'yup': 7648,
 'elaborating': 2562,
 'safety': 5823,
 'aspects': 1108,
 'and': 970,
 'other': 4962,
 'issues': 3753,
 'lor': 4195,
 'anyway': 1013,
 'thk': 6780,
 'we': 7330,
 'cant': 1651,
 'tickets': 6813,
 'cos': 2023,
 'like': 4103,
 'quite': 5480,
 'late': 4017,
 'already': 930,
 'wan': 7289,
 'go': 3164,
 'look': 4185,
 'frens': 3002,
 'darren': 2175,
 'them': 6747,
 'helloooo': 3402,
 'wake': 7274,
 'sweet': 6582,
 'morning': 4564,
 'welcomes': 7369,
 'enjoy': 2608,
 'this': 6779,
 'full': 3045,
 'joy': 3848,
 'gud': 3270,
 'mrng': 4588,
 'pls': 5212,
 'da': 2149,
 'what': 7391,
 'happen': 3326,
 '09094100151': 240,
 'use': 7138,
 'calls': 1632,
 'cast': 1686,
 '10p': 264,
 'min': 4463,
 'mob': 4518,
 'vary': 7175,
 'service': 5976,
 'provided': 5420,
 'aom': 1016,
 'gbp5': 3101,
 'month': 4553,
 'box61': 1477,
 'm60': 4271,
 '1er': 329,
 'until': 7100,
 'stop': 6435,
 'ages': 874,
 '18': 319,
 'are': 1057,
 'awake': 1174,
 'there': 6756,
 'snow': 6226,
 'hmph': 3458,
 'head': 3369,
 'big': 1354,
 'baller': 1215,
 'gonna': 3186,
 'be': 1279,
 'at': 1119,
 'blake': 1387,
 'night': 4746,
 'might': 4455,
 'able': 759,
 'little': 4144,
 'early': 2509,
 'thanx': 6732,
 'lot': 4203,
 'oh': 4879,
 'ic': 3582,
 'thought': 6788,
 'meant': 4399,
 'mary': 4352,
 'jane': 3788,
 'tv': 6999,
 'watch': 7312,
 'meh': 4415,
 'work': 7509,
 'today': 6861,
 'want': 7293,
 'new': 4728,
 'video': 7200,
 'phone': 5147,
 '750': 623,
 'anytime': 1012,
 'any': 1004,
 'network': 4721,
 'price': 5354,
 'line': 4117,
 'rental': 5647,
 'text': 6710,
 'months': 4556,
 'reply': 5661,
 '08000930705': 48,
 'delivery': 2243,
 'notice': 4798,
 'looking': 4189,
 'shit': 6042,
 'mirror': 4482,
 'youre': 7629,
 'turning': 6997,
 'into': 3714,
 'right': 5725,
 'freak': 2987,
 'management': 4321,
 'puzzeles': 5461,
 'tension': 6694,
 'face': 2749,
 'smiling': 6204,
 'waste': 7308,
 'innocent': 3687,
 'terror': 6702,
 'cruel': 2092,
 'romantic': 5761,
 'lovable': 4216,
 'decent': 2207,
 'joker': 3835,
 'sunny': 6539,
 'california': 1616,
 'weather': 7338,
 'cool': 2009,
 'fyi': 3063,
 'usf': 7144,
 'room': 5763,
 'whenever': 7399,
 'asked': 1101,
 'sen': 5952,
 'chennai': 1776,
 'search': 5913,
 'job': 3824,
 'it': 3755,
 'flood': 2910,
 'pretty': 5349,
 'pussy': 5457,
 'cum': 2120,
 'going': 3176,
 'esplanade': 2657,
 'home': 3477,
 'an': 966,
 'customer': 2134,
 'announcement': 985,
 'freephone': 2997,
 '0800': 45,
 '542': 561,
 '0825': 59,
 'how': 3522,
 'wish': 7457,
 'great': 3237,
 'semester': 5950,
 'hi': 3426,
 'happy': 3335,
 'birthday': 1373,
 'opinion': 4930,
 'something': 6254,
 'first': 2883,
 'done': 2410,
 'internet': 3710,
 'connection': 1975,
 'slow': 6184,
 'try': 6975,
 'again': 865,
 'later': 4020,
 'thing': 6769,
 'tomo': 6878,
 'anything': 1011,
 'am': 942,
 'film': 2855,
 '2day': 386,
 '6pm': 612,
 'sorry': 6278,
 'put': 5458,
 'box': 1463,
 'dai': 2156,
 'resume': 5699,
 'id': 3590,
 'yes': 7607,
 'appt': 1046,
 'mean': 4395,
 'she': 6018,
 'told': 6870,
 'hr': 3533,
 'posting': 5289,
 'because': 1290,
 'working': 7513,
 'know': 3953,
 'why': 7419,
 'god': 3170,
 'created': 2072,
 'gap': 3081,
 'between': 1343,
 'fingers': 2869,
 'so': 6230,
 'one': 4909,
 'who': 7411,
 'made': 4291,
 'amp': 959,
 'fills': 2854,
 'those': 6786,
 'gaps': 3082,
 'holding': 3470,
 'hand': 3311,
 'slide': 6175,
 'enough': 2614,
 'bless': 1394,
 'good': 3188,
 'sleep': 6165,
 'dear': 2199,
 'pray': 5320,
 'called': 1624,
 'pick': 5158,
 'ask': 1099,
 'both': 1453,
 'they': 6764,
 'said': 5825,
 'finish': 2870,
 'mon': 4542,
 'thurs': 6807,
 'cash': 1682,
 'balance': 1213,
 'currently': 2129,
 'pounds': 5297,
 'maximize': 4382,
 '86688': 689,
 '150p': 303,
 'msg': 4591,
 'cc': 1702,
 '08718720201': 129,
 'hg': 3425,
 'suite342': 6524,
 '2lands': 398,
 'row': 5774,
 'w1j6hl': 7254,
 'babe': 1192,
 'dont': 2412,
 'baby': 1194,
 'im': 3619,
 'nasty': 4671,
 'filthyguys': 2858,
 'fancy': 2779,
 'rude': 5788,
 'time': 6822,
 'sexy': 5992,
 'bitch': 1376,
 'about': 761,
 'slo': 6180,
 'hard': 3336,
 'txt': 7010,
 'xxx': 7575,
 '4msgs': 528,
 'noe': 4768,
 'wat': 7311,
 'place': 5184,
 'dat': 2178,
 'sells': 5948,
 '4d': 522,
 'closes': 1860,
 'joys': 3849,
 'lifeis': 4093,
 'waking': 7275,
 'each': 2505,
 'daywith': 2189,
 'thoughts': 6789,
 'somewheresomeone': 6260,
 'cares': 1670,
 'tosend': 6909,
 'warm': 7300,
 'greeting': 3243,
 'juz': 3873,
 'remembered': 5632,
 'gotta': 3208,
 'bathe': 1255,
 'dog': 2391,
 'went': 7375,
 'project': 5397,
 'centre': 1718,
 'financial': 2863,
 'problem': 5378,
 'help': 3403,
 'gift': 3137,
 'yoyyooo': 7637,
 'change': 1732,
 'permissions': 5119,
 'drive': 2458,
 'mac': 4278,
 'usb': 7136,
 'flash': 2898,
 'watching': 7315,
 'house': 3517,
 'very': 7191,
 'entertaining': 2620,
 'getting': 3131,
 'whole': 7413,
 'hugh': 3543,
 'laurie': 4028,
 'even': 2672,
 'stick': 6421,
 'indeed': 3662,
 'especially': 2656,
 'explicit': 2731,
 'sex': 5989,
 '30': 429,
 'secs': 5924,
 'ring': 5730,
 '02073162414': 11,
 'costs': 2027,
 '20p': 355,
 'gsex': 3262,
 'pobox': 5221,
 '2667': 374,
 'wc1n': 7328,
 '3xx': 482,
 'borrow': 1449,
 'bag': 1204,
 'ringtone': 5733,
 '87131': 696,
 'poly': 5247,
 'true': 6968,
 'tone': 6882,
 '0845': 64,
 '2814032': 378,
 '16': 314,
 'after': 858,
 '1st': 336,
 'tones': 6883,
 '3x': 481,
 '150pw': 309,
 'nd': 4687,
 'hopefully': 3493,
 'den': 2248,
 'schedule': 5884,
 'lk': 4150,
 'sun': 6534,
 'uh': 7034,
 'heads': 3373,
 'don': 2408,
 'much': 4608,
 'left': 4059,
 'live': 4145,
 '121': 278,
 'chat': 1752,
 '60p': 580,
 'choose': 1812,
 'girl': 3144,
 'connect': 1973,
 '09094646899': 241,
 'cheap': 1757,
 'uk': 7038,
 'biggest': 1356,
 'vu': 7249,
 'bcm1896wc1n3xx': 1272,
 'sir': 6130,
 'waiting': 7273,
 'once': 4907,
 'planning': 5193,
 'usually': 7149,
 'stops': 6438,
 'hella': 3400,
 'weed': 7352,
 'smoke': 6206,
 'nt': 4813,
 'joking': 3838,
 'seriously': 5973,
 'ranjith': 5516,
 'cal': 1612,
 'drpd': 2468,
 'deeraj': 2222,
 'deepak': 2220,
 '5min': 566,
 'hold': 3468,
 'give': 3150,
 'walk': 7278,
 'was': 7305,
 'bathroom': 1257,
 'sup': 6545,
 'aiyar': 895,
 'type': 7024,
 'then': 6751,
 'tell': 6679,
 'scold': 5888,
 'takin': 6620,
 'linear': 4118,
 'algebra': 913,
 'private': 5368,
 '2003': 348,
 'account': 789,
 'statement': 6400,
 'shows': 6082,
 '800': 638,
 'un': 7047,
 'redeemed': 5593,
 'points': 5241,
 '08718738001': 141,
 'identifier': 3596,
 'code': 1887,
 '49557': 519,
 'expires': 2728,
 '26': 373,
 '11': 267,
 '04': 15,
 'lovly': 4229,
 'ho': 3461,
 'these': 6758,
 'words': 7508,
 'talking': 6627,
 'keeping': 3899,
 'away': 1177,
 'means': 4398,
 'still': 6424,
 'think': 6771,
 'teju': 6675,
 'cheers': 1770,
 'tex': 6709,
 'mecause': 4403,
 'werebored': 7378,
 'okden': 4887,
 'hunny': 3556,
 'uin': 7036,
 'wk': 7473,
 'sat': 5856,
 'sound': 6288,
 'likeyour': 4107,
 'havin': 3364,
 'gr8fun': 3216,
 'keep': 3898,
 'updat': 7106,
 'countinlots': 2036,
 'loveme': 4221,
 'xxxxx': 7578,
 'eat': 2520,
 'tonight': 6888,
 'purity': 5450,
 'friendship': 3014,
 'two': 7008,
 'reading': 5542,
 'forwarded': 2970,
 'seeing': 5930,
 'name': 4658,
 'evng': 2693,
 'shoot': 6055,
 'docs': 2383,
 'continued': 1994,
 'support': 6552,
 'question': 5473,
 'week': 7353,
 'enter': 2616,
 'in2': 3644,
 'our': 4967,
 'draw': 2445,
 '100': 253,
 'us': 7134,
 'president': 5341,
 'ans': 991,
 '80082': 642,
 'error': 2645,
 'fucking': 3038,
 'too': 6892,
 'fuck': 3035,
 'hear': 3380,
 'voice': 7237,
 'need': 4700,
 'crave': 2065,
 'adore': 828,
 'ahmad': 884,
 'kisses': 3940,
 'erm': 2641,
 'ill': 3615,
 '45pm': 511,
 'park': 5045,
 'dun': 2490,
 'sch': 5883,
 'beautiful': 1286,
 'truth': 6974,
 'against': 866,
 'gravity': 3234,
 'read': 5540,
 'carefully': 1668,
 'heart': 3384,
 'feels': 2818,
 'light': 4099,
 'someone': 6249,
 'heavy': 3391,
 'leaves': 4054,
 'goodmorning': 3192,
 'won': 7492,
 '000': 1,
 'prize': 5371,
 'claim': 1830,
 'call09050000327': 1618,
 'rstm': 5781,
 'sw7': 6572,
 '3ss': 478,
 '150ppm': 307,
 'wil': 7431,
 'horrible': 3502,
 'gal': 3071,
 'knew': 3949,
 'him': 3436,
 'yest': 7608,
 'as': 1090,
 'sim': 6113,
 'subscriber': 6498,
 'selected': 5940,
 'receive': 5570,
 'bonus': 1432,
 'delivered': 2241,
 'door': 2419,
 'word': 7507,
 '88600': 706,
 'exp': 2717,
 '30apr': 436,
 'shower': 6077,
 'hey': 3423,
 'fri': 3006,
 'miwa': 4501,
 'jiayin': 3818,
 'leave': 4053,
 'karaoke': 3889,
 'ex': 2698,
 'wife': 7426,
 'kids': 3923,
 'wamma': 7288,
 'laid': 3991,
 'real': 5544,
 'doggin': 2394,
 'locations': 4164,
 'sent': 5963,
 'mobile': 4519,
 'join': 3831,
 'uks': 7040,
 'largest': 4013,
 'dogging': 2395,
 'dogs': 2397,
 '69696': 599,
 'nyt': 4838,
 'ec2a': 2525,
 '3lp': 470,
 '50': 542,
 'nothing': 4797,
 'money': 4545,
 'enters': 2618,
 'bank': 1225,
 'remove': 5641,
 'flat': 2899,
 'rate': 5519,
 'transfered': 6940,
 'dollars': 2405,
 'removed': 5642,
 'banks': 1226,
 'differ': 2316,
 'charges': 1743,
 'also': 933,
 'trust': 6973,
 '9ja': 739,
 'sending': 5955,
 'details': 2280,
 'missing': 4490,
 'sender': 5954,
 'number': 4821,
 'date': 2179,
 'thats': 6737,
 'everything': 2687,
 'via': 7193,
 'fullonsms': 3046,
 'com': 1909,
 'prof': 5389,
 'passed': 5061,
 'papers': 5032,
 'sem': 5949,
 'congrats': 1970,
 'student': 6470,
 'enna': 2613,
 'kalaachutaarama': 3881,
 'ah': 879,
 'plus': 5214,
 'workin': 7512,
 'oso': 4961,
 'rite': 5742,
 'orchard': 4946,
 'liao': 4083,
 'yay': 7595,
 'finally': 2861,
 'lol': 4175,
 'missed': 4488,
 'cinema': 1825,
 'trip': 6959,
 'last': 4015,
 'kallis': 3884,
 'ground': 3254,
 'amla': 950,
 'durban': 2494,
 'havent': 3362,
 'probably': 5377,
 'pop': 5263,
 'weekend': 7355,
 'did': 2307,
 'miss': 4487,
 'worry': 7520,
 'guess': 3273,
 'busy': 1586,
 'sentence': 5964,
 'concentrate': 1952,
 'educational': 2535,
 'career': 1665,
 'leaving': 4055,
 'kano': 3887,
 'whr': 7418,
 'treat': 6953,
 'maga': 4295,
 'trouble': 6965,
 'buy': 1591,
 'dad': 2153,
 '1405': 293,
 '1680': 316,
 '1843': 321,
 'small': 6191,
 'order': 4947,
 'reference': 5597,
 'x29': 7562,
 'charged': 1742,
 'should': 6069,
 'arrive': 1080,
 'services': 5977,
 '09065989180': 218,
 '07734396839': 28,
 'ibh': 3575,
 'loyalty': 4235,
 'offer': 4866,
 'nokia6600': 4774,
 '10': 252,
 'txtauction': 7014,
 'start': 6392,
 '81151': 653,
 'yours': 7631,
 '4t': 531,
 'tht': 6804,
 'incident': 3648,
 'flippin': 2906,
 'yet': 7610,
 'paper': 5031,
 'princess': 5359,
 'every': 2679,
 'command': 1921,
 'were': 7377,
 'thinking': 6774,
 'staying': 6407,
 'mcr': 4391,
 'had': 3295,
 'contract': 1995,
 'mnths': 4515,
 'latest': 4021,
 'etc': 2661,
 'double': 2427,
 'orange': 4943,
 'tariffs': 6637,
 'callback': 1620,
 'records': 5585,
 'excellent': 2703,
 'together': 6865,
 'pleased': 5206,
 'advise': 841,
 'following': 2933,
 'recent': 5574,
 'review': 5713,
 'awarded': 1176,
 '1500': 302,
 '09066364589': 227,
 'almost': 926,
 'forgot': 2957,
 'ya': 7584,
 'ard': 1056,
 'reach': 5535,
 'sometimes': 6256,
 'walls': 7285,
 'around': 1076,
 'hearts': 3386,
 'safe': 5821,
 'hurt': 3561,
 'break': 1500,
 'closer': 1859,
 'goodnoon': 3195,
 'remember': 5631,
 'old': 4896,
 'commercial': 1923,
 'shopping': 6058,
 'present': 5340,
 'started': 6393,
 'guessing': 3276,
 'guessed': 3274,
 'decide': 2208,
 'vikky': 7209,
 'olave': 4895,
 'mandara': 4325,
 'movie': 4581,
 'trishul': 6962,
 'theatre': 6742,
 'wit': 7464,
 'her': 3414,
 'stay': 6404,
 'been': 1302,
 'tough': 6918,
 'optimistic': 4936,
 'improve': 3640,
 'dude': 2482,
 'buff': 1560,
 'wind': 7439,
 'year': 7597,
 'alright': 931,
 'advice': 840,
 'ma': 4275,
 'showing': 6080,
 'cld': 1841,
 'drink': 2453,
 'before': 1307,
 'wld': 7480,
 'prefer': 5328,
 'spend': 6323,
 'nosh': 4792,
 'mind': 4465,
 'doing': 2400,
 'nxt': 4834,
 'sef': 5936,
 'dey': 2292,
 'laugh': 4024,
 'meanwhile': 4400,
 'darling': 2173,
 'anjie': 979,
 'sooooo': 6274,
 'bed': 1296,
 'lonely': 4180,
 'dream': 2447,
 'smsing': 6214,
 'xy': 7582,
 'neva': 4724,
 'sort': 6279,
 'meet': 4408,
 'bring': 1520,
 'along': 928,
 'next': 4737,
 'meeting': 4410,
 'well': 7370,
 'confuses': 1969,
 'doesn': 2389,
 'kate': 3891,
 'asap': 1092,
 'run': 5799,
 'frm': 3017,
 'slowly': 6187,
 'kills': 3929,
 'convey': 2001,
 'regards': 5611,
 'wouldn': 7532,
 'hour': 3514,
 'least': 4052,
 'ujhhhhhhh': 7037,
 'computer': 1948,
 'shipped': 6038,
 'address': 819,
 'sandiago': 5840,
 'parantella': 5038,
 'lane': 4002,
 'wtf': 7551,
 'poop': 5259,
 'toledo': 6871,
 'say': 5873,
 'clean': 1842,
 'blood': 1408,
 'ten': 6690,
 'special': 6311,
 'people': 5104,
 'miracle': 4481,
 'oredi': 4951,
 'telugu': 6685,
 'abt': 768,
 'hello': 3401,
 'handsome': 3317,
 'finding': 2865,
 'being': 1318,
 'lazy': 4037,
 'towards': 6921,
 'mummy': 4620,
 'where': 7401,
 'boytoy': 1485,
 'does': 2387,
 'elaine': 2563,
 'evening': 2673,
 'hope': 3490,
 'having': 3365,
 'nice': 4741,
 'wanted': 7295,
 'rent': 5646,
 'past': 5066,
 'few': 2829,
 'charge': 1741,
 'felt': 2823,
 'would': 7530,
 'inconsiderate': 3655,
 'nag': 4651,
 'cost': 2024,
 'yourself': 7632,
 'didnt': 2310,
 'speak': 6309,
 'however': 3526,
 'recession': 5577,
 'wont': 7499,
 'hence': 3411,
 'askin': 1102,
 'ahead': 881,
 'end': 2592,
 'thank': 6727,
 'download': 2432,
 'fring': 3016,
 'app': 1026,
 'yar': 7589,
 'raining': 5497,
 'non': 4777,
 'elsewhere': 2574,
 'total': 6913,
 'disappointment': 2348,
 'texted': 6716,
 'craziest': 2067,
 'city': 1827,
 'could': 2032,
 'win': 7437,
 '200': 346,
 'summer': 6530,
 'spree': 6359,
 'store': 6441,
 '88039': 702,
 'skilgme': 6149,
 'tscs087147403231winawk': 6981,
 'age16': 869,
 '50perwksub': 549,
 'battery': 1260,
 'died': 2312,
 'gram': 3221,
 '3g': 466,
 'videophones': 7202,
 '09061744553': 196,
 'videochat': 7201,
 'wid': 7423,
 'mates': 4365,
 'play': 5196,
 'java': 3795,
 'games': 3076,
 'dload': 2374,
 'polyh': 5250,
 'music': 4629,
 ...}

In [ ]:
vectorizer.get_feature_names_out()[1743]

'charges'

In [ ]:
y_train

184     0
2171    0
5422    0
4113    0
4588    0
       ..
1932    0
5316    0
2309    1
1904    1
762     0
Name: spam, Length: 4457, dtype: int64

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = vectorizer.transform(X_test.values)
y_pred = model.predict(X_test_cv)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

FP => Prediction = Positive Actual = Negative

Means the model predicts the mail is spam but actually the mail is important and urgent to respond.

In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print(precision)

0.9855072463768116

In [ ]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
emails = [
    'Hi Priya, can we have a meeting tomorrow?',
    'Upto 20% OFF on H&M. Dont miss this exclusive reward'
]

emails_vectorizer = vectorizer.transform(emails)
model.predict(emails_vectorizer)

array([0, 1])

Raw TF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

reviews = [
    'The plot is good.',
    'The plot is good, good, really good.'
]

tf_vectorizer = TfidfVectorizer(use_idf=False)

tf_matrix = tf_vectorizer.fit_transform(reviews)
tf_matrix.toarray()
df_tf_vectorizer = pd.DataFrame(tf_matrix.toarray(), columns = tf_vectorizer.get_feature_names_out())

df_tf_vectorizer

      good       is     plot   really      the
0  0.50000  0.50000  0.50000  0.00000  0.50000
1  0.83205  0.27735  0.27735  0.27735  0.27735

'is', 'the', 'a' [high frequency] => tf_vectorizer values will be also high

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

reviews = [
    'The plot is good.',
    'The plot is good, good, really good.'
    'The plot is a masterpiece',
    'I hate the plot',
    'The plot is okay'
]

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(reviews)
tfidf_matrix.toarray()
df_tfidf_vectorizer = pd.DataFrame(tfidf_matrix.toarray(), columns = tfidf_vectorizer.get_feature_names_out())

df_tfidf_vectorizer

,good,hate,is,masterpiece,okay,plot,really,the
0,0.628493,0.000000,0.508819,0.000000,0.000000,0.415993,0.000000,0.415993
1,0.700444,0.000000,0.378047,0.296142,0.000000,0.309078,0.296142,0.309078
2,0.000000,0.804612,0.000000,0.000000,0.000000,0.419880,0.000000,0.419880
3,0.000000,0.000000,0.456847,0.000000,0.715739,0.373502,0.000000,0.373502